### ISSUE TITLE
Report and handle properly error when cinema database path is invalid

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_jnc#1]
If any Cinema Database requested is not found, the widget should report this properly, and not display anything.

**Comment by dbanesh** [comment]
There is now an initial check to determine if the path to a cdb directory is valid. If it is not, the code prints an error message that "xx.cdb does not exists" and exits. The code DOES NOT:
1. Check if multiple directories are invalid. It exits after the first invalid path found.
2. Check if the contents of the directory are invalid. It's possible that the contents of the directory (either the data.csv or a particular path to an image) is broken and this would result in a runtime error.

If either of these cases should be handled, please let me know. At the moment, the issue only says to check if database path is invalid.

**Comment by dhrogers** [comment]
This is fine for now. We should include database checking in the cinemasci module, and when that is implemented, we can add that capability here for free.
