### ISSUE TITLE
Add capability to set and retrieve the settings for any set of parameters

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_jnc#5]
Include calls:

viewer.setParameterValues({'name01': 'value', 'name02': 'value', ...})
    sets parameters provided and updates the view
viewer.getParameterValues()
    returns a dict of all parameters and current values
viewer.getParameterValue( name )
    returns the current value of the named parameter, None if parameter is not present

**Comment by dbanesh** [comment]
Just to clarify, 'parameters' here refers to the parameters of the cinema database. E.g.: phi, theta, time,.... ?

**Comment by dhrogers** [comment]
@dbanesh yes.

**Comment by dbanesh** [comment]
@dhrogers getters and setters have been added. Few examples of their use are in cinema_module. The setter checks if the the value provided is an option of the parameter; if not, it prints a message saying so.
