### ISSUE TITLE
Add capability to hide and show parameter controls

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_jnc#6]
Add the following calls:

viewer.hideParameterControl( name )
    hides the parameter control and updates the view
    returns true if the parameter existed and was hidden; false if the parameter does not exist
viewer.showParameterControl( name)
    shows the parameter control and updates the view
    returns true if the parameter exists and was shown; false if the parameter does not exist

**Comment by dhrogers** [comment]
Also include the following call:

viewer.getParameterNames()
    returns a list of all parameters

**Comment by dhrogers** [comment]
I believe there should be two classes of values: parameters (from the cinema database), and properties of the viewer (image width, layout type, etc.)

So these should apply only to parameters, but we should have controls for the properties as well. At the moment that would include a set of controls (hide, show, get, set) for the image size property.

**Comment by dbanesh** [comment]
@dhr hide and show parameter functionality has been added

**Comment by dbanesh** [comment]
@getParameterNames() has been added

**Comment by dbanesh** [comment]
@dhrogers I also added a getParameterOptions(name) function. If the user wants to set the parameter values to something, it might be helpful to know what the options are....

**Comment by dbanesh** [comment]
@dhrogers hide,show, getters, setters for ui are implemented.
