### ISSUE TITLE
Integrate CI testing

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_jnc#7]
We need to have CI testing for this module.

@EthanS94 : can we use the cinema_module notebook for testing, or is there a better way to test UI-based jupyter notebook stuff?

**Comment by EthanS94** [comment]
@dhrogers Sorry I missed this. Thanks @dbanesh for pointing this out in the meeting! I am not sure how capable Travis is with UI's, but I'll look into it and have a response by the cinema meeting.

**Comment by dhrogers** [comment]
Thanks @EthanS94

**Comment by EthanS94** [comment]
Here's one idea. Using `jupyter nbconvert --execute cinema_module.ipynb` will execute all cells and write out an equivalent html file. There's no GUI interaction, but it seems easy to put in a test. @dhrogers Thoughts on this?

**Comment by dhrogers** [comment]
@dbanesh @EthanS94 : I've looked into this a bit and I don't see a good solution as the code is currently designed. The `nbconvert` option outputs a file that includes what appears to be an automatically generated ID on almost everything, so a straight comparison would not work. We could write some code to remove that, but that seems like a fragile option.

If we refactor the code, we can do some unit testing that would exercise things in the normal `python -m unttest` way, and that's likely a better option.

I'll talk with @dbanesh about this option, but in the meantime I will implement a small test so that @EthanS94 can hook up travis for this.

**Comment by dhrogers** [comment]
@EthanS94 @dbanesh : I added a very simple test that creates a `CinemaView` object. It doesn't load a database, because there are problems in creating the display context, but this at least loads the module and creates an object.

Ethan - can you do initial CIS integration on this?

Thanks

**Comment by EthanS94** [comment]
Yeah this will work. Thanks.

**Comment by EthanS94** [comment]
Added travis and the first test passed, so I am closing this one
